//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        decimal Suma(decimal x, decimal y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> SumaAsync(decimal x, decimal y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        decimal Resta(decimal x, decimal y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> RestaAsync(decimal x, decimal y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        decimal Multiplicacion(decimal x, decimal y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> MultiplicacionAsync(decimal x, decimal y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        decimal Division(decimal x, decimal y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> DivisionAsync(decimal x, decimal y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.WebService1Soap>, WebApplication2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Suma(decimal x, decimal y) {
            return base.Channel.Suma(x, y);
        }
        
        public System.Threading.Tasks.Task<decimal> SumaAsync(decimal x, decimal y) {
            return base.Channel.SumaAsync(x, y);
        }
        
        public decimal Resta(decimal x, decimal y) {
            return base.Channel.Resta(x, y);
        }
        
        public System.Threading.Tasks.Task<decimal> RestaAsync(decimal x, decimal y) {
            return base.Channel.RestaAsync(x, y);
        }
        
        public decimal Multiplicacion(decimal x, decimal y) {
            return base.Channel.Multiplicacion(x, y);
        }
        
        public System.Threading.Tasks.Task<decimal> MultiplicacionAsync(decimal x, decimal y) {
            return base.Channel.MultiplicacionAsync(x, y);
        }
        
        public decimal Division(decimal x, decimal y) {
            return base.Channel.Division(x, y);
        }
        
        public System.Threading.Tasks.Task<decimal> DivisionAsync(decimal x, decimal y) {
            return base.Channel.DivisionAsync(x, y);
        }
    }
}
